---
- name: add docker GPG
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: add doker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present
  tags: docker

- name: update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest
  tags: docker

- name: intall docker & docker compose
  pip:
   name: 
      - docker
      - docker-compose
  tags: docker

- name: set docker-compose
  template:
    src: docker-compose.yml.j2
    dest: docker-compose.yml
  tags: docker

- name: run docker compose
  become: True
  shell:
    cmd: "docker-compose -f docker-compose.yml up -d"
  tags: docker